ConsumeWebApi/Models/Saldo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConsumeWebApi.Models
{
    public class Saldo
    {
        public decimal ingreso { get; set; }
    }
}

ConsumeWebApi/Models/Wallet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConsumeWebApi.Models
{
    public class Wallet
    {
        public bool State { get; set; }
        public decimal Money { get; set; }
        public string Message { get; set; }
    }
}

ConsumeWebApi/Controllers/WalletController.cs
using ConsumeWebApi.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ConsumeWebApi.Controllers
{
    public class WalletController : Controller
    {
        string BaseUrl = "http://localhost:8090/";

        // GET: Wallet
        public async Task<ActionResult> Index()
        {
            List<Wallet> wallet = new List<Wallet>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage res = await client.GetAsync("api/wallet/getmoney");
                if (res.IsSuccessStatusCode)
                {
                    var empResponse = res.Content.ReadAsStringAsync().Result;

                    wallet = JsonConvert.DeserializeObject<List<Wallet>>(empResponse);
                }
            }

            return View(wallet);
        }
        
        public ActionResult AgregarSaldo()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegistrarSaldo(decimal ingreso)
        {
            Wallet wallet = new Wallet();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage res = await client.GetAsync("api/wallet/addMoney/"+ ingreso +"/");
                if (res.IsSuccessStatusCode)
                {
                    var empResponse = res.Content.ReadAsStringAsync().Result;

                    wallet = JsonConvert.DeserializeObject<Wallet>(empResponse);
                }
            }

            return RedirectToAction("Index");
        }


        public ActionResult RetirarSaldo()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegistrarSalidaDeSaldo(decimal ingreso)
        {
            Wallet wallet = new Wallet();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(BaseUrl);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage res = await client.GetAsync("api/wallet/subtractMoney/" + ingreso + "/");
                if (res.IsSuccessStatusCode)
                {
                    var empResponse = res.Content.ReadAsStringAsync().Result;

                    wallet = JsonConvert.DeserializeObject<Wallet>(empResponse);
                }
            }
            return RedirectToAction("Index");
        }

    }
}

ConsumeWebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Banca", "Index", "Wallet", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rosember Carrasco Sumoya</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ConsumeWebApi/Views/Wallet/AgregarSaldo.cshtml
@model ConsumeWebApi.Models.Saldo

@{
    ViewBag.Title = "Agregar Saldo";
}

<h2>Agregar Saldo</h2>


@using (Html.BeginForm("RegistrarSaldo", "Wallet")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Saldo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ingreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ingreso, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" name="agregar" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConsumeWebApi/Views/Wallet/Index.cshtml
@model IEnumerable<ConsumeWebApi.Models.Wallet>

@{
    ViewBag.Title = "Estado de cuenta";
}

<h2>Cuenta:</h2>

<p>
    @Html.ActionLink("Agregar Saldo", "AgregarSaldo")
    <br/>
    <br/>
    @Html.ActionLink("Retirar Saldo", "RetirarSaldo")

</p>

<br/>
<label class="control-label col-md-2" name="status">@Model.Last().State </label>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Money)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Money)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
        
    </tr>
}

</table>

ConsumeWebApi/Views/Wallet/RetirarSaldo.cshtml
@model ConsumeWebApi.Models.Saldo

@{
    ViewBag.Title = "Retirar Saldo";
}

<h2>Retirar Saldo</h2>


@using (Html.BeginForm("RegistrarSalidaDeSaldo", "Wallet")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Egreso</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Monto de retiro:</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ingreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Restar" class="btn btn-default" name="restar"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>